In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('train.csv')

In [3]:
train

,V1.1,V1.2,V1.3,V1.4,V1.5,V1.6,V1.7,V1.8,V1.9,V1.10,...,y1,t,prob_t,y,prob_t_pred_log,prob_t_pred_tree,linear0,lasso0,linear1,lasso1
0,0,0,1,1,1,1,1,1,1,1,...,0.614564,0,0.5,0.642541,0.540735,0.534,0.651443,0.606851,0.618742,0.593018
1,0,0,0,0,1,1,1,1,1,1,...,0.444755,1,0.5,0.444755,0.472217,0.466,0.384518,0.447153,0.432265,0.506971
2,0,0,0,0,0,0,0,0,0,1,...,0.768312,1,0.5,0.768312,0.457727,0.466,0.674254,0.567190,0.778391,0.596438
3,0,0,0,0,0,1,1,1,1,1,...,0.529249,1,0.5,0.529249,0.467140,0.466,0.487258,0.498000,0.532671,0.539307
4,0,0,0,0,0,1,1,1,1,1,...,0.524217,0,0.5,0.444901,0.532745,0.534,0.484653,0.495063,0.534569,0.538366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1,1,1,1,1,1,1,1,1,1,...,0.221919,0,0.5,0.210285,0.519832,0.534,0.226593,0.385518,0.233375,0.458485
496,0,0,0,0,0,1,1,1,1,1,...,0.423432,0,0.5,0.374812,0.526189,0.534,0.350192,0.417442,0.433016,0.495229
497,0,0,0,0,0,1,1,1,1,1,...,0.402069,0,0.5,0.341317,0.525551,0.534,0.337216,0.410499,0.421738,0.491106
498,0,0,0,0,0,0,1,1,1,1,...,0.680295,0,0.5,0.691818,0.542143,0.534,0.676524,0.598133,0.700218,0.599353
499,0,0,0,0,0,0,0,1,1,1,...,0.371567,1,0.5,0.371567,0.478020,0.466,0.262575,0.358521,0.389333,0.466505

In [5]:
train.sample(50).to_csv('train_50.csv', index=False)

In [6]:
test = pd.read_csv('test.csv')

In [7]:
test.sample(100).to_csv('test_100.csv', index=False)

In [8]:
len(test)

10000

In [10]:
train[['lasso1', 'lasso1']]

       lasso1    lasso1
0    0.593018  0.593018
1    0.506971  0.506971
2    0.596438  0.596438
3    0.539307  0.539307
4    0.538366  0.538366
..        ...       ...
495  0.458485  0.458485
496  0.495229  0.495229
497  0.491106  0.491106
498  0.599353  0.599353
499  0.466505  0.466505

[500 rows x 2 columns]